# Company -> (ticker, [regex keyword patterns]). Word-boundary, case-insensitive.
# Only US-listed / ADR-tradable tickers with Yahoo daily data.
COMPANIES = {
    "Apple": ("AAPL", [r"\bapple\b", r"\btim cook\b"]),
    "Nvidia": ("NVDA", [r"\bnvidia\b", r"\bjensen huang\b"]),
    "Tesla": ("TSLA", [r"\btesla\b", r"\belon musk\b(?!.{0,40}twitter)"]),
    "Boeing": ("BA", [r"\bboeing\b"]),
    "Dell": ("DELL", [r"\bdell\b"]),
    "US Steel": ("X", [r"\bu\.?s\.? steel\b", r"\bunited states steel\b"]),
    "Palantir": ("PLTR", [r"\bpalantir\b"]),
    "Eli Lilly": ("LLY", [r"\beli lilly\b", r"\blilly\b"]),
    "GE Aerospace": ("GE", [r"\bge aerospace\b", r"\bgeneral electric\b"]),
    "American Eagle": ("AEO", [r"\bamerican eagle\b", r"\bsydney sweeney\b"]),
    "Amazon": ("AMZN", [r"\bamazon\b"]),
    "Meta": ("META", [r"\bfacebook\b", r"\bmeta\b", r"\bzuckerberg\b", r"\binstagram\b"]),
    "Alphabet": ("GOOGL", [r"\bgoogle\b", r"\balphabet\b", r"\bsundar pichai\b", r"\byoutube\b"]),
    "Microsoft": ("MSFT", [r"\bmicrosoft\b", r"\bbill gates\b"]),
    "Pfizer": ("PFE", [r"\bpfizer\b"]),
    "Ford": ("F", [r"\bford motor\b", r"\bford\b"]),
    "General Motors": ("GM", [r"\bgeneral motors\b", r"\bmary barra\b"]),
    "Harley-Davidson": ("HOG", [r"\bharley[- ]?davidson\b", r"\bharley\b"]),
    "Goodyear": ("GT", [r"\bgoodyear\b"]),
    "Anheuser-Busch": ("BUD", [r"\bbud light\b", r"\banheuser\b", r"\bbudweiser\b"]),
    "Coca-Cola": ("KO", [r"\bcoca[- ]?cola\b", r"\bdiet coke\b", r"\bcoca cola\b"]),
    "Disney": ("DIS", [r"\bdisney\b", r"\babc news\b", r"\bespn\b", r"\biger\b"]),
    "Comcast": ("CMCSA", [r"\bcomcast\b", r"\bmsnbc\b", r"\bnbc\b"]),
    "Nike": ("NKE", [r"\bnike\b"]),
    "Walmart": ("WMT", [r"\bwalmart\b", r"\bwal-mart\b"]),
    "Home Depot": ("HD", [r"\bhome depot\b"]),
    "Lockheed Martin": ("LMT", [r"\blockheed\b"]),
    "Exxon": ("XOM", [r"\bexxon\b"]),
    "Intel": ("INTC", [r"\bintel corp\b", r"\bintel\b"]),
    "AT&T": ("T", [r"\bat&t\b", r"\bat and t\b"]),
    "Verizon": ("VZ", [r"\bverizon\b"]),
    "JPMorgan": ("JPM", [r"\bjpmorgan\b", r"\bjp morgan\b", r"\bjamie dimon\b"]),
    "TSMC": ("TSM", [r"\btsmc\b", r"\btaiwan semiconductor\b"]),
    "SoftBank": ("SFTBY", [r"\bsoftbank\b", r"\bmasayoshi son\b"]),
    "Paramount": ("PARA", [r"\bparamount\b", r"\bcbs\b", r"\b60 minutes\b"]),
    "Netflix": ("NFLX", [r"\bnetflix\b"]),
    "Warner Bros Discovery": ("WBD", [r"\bcnn\b", r"\bwarner bros\b", r"\bwarner brothers\b"]),
    "Fox Corp": ("FOXA", [r"\bfox news\b", r"\bfox corp\b"]),
    "Starbucks": ("SBUX", [r"\bstarbucks\b"]),
    "McDonald's": ("MCD", [r"\bmcdonald\b", r"\bmcdonald's\b"]),
    "Target": ("TGT", [r"\btarget corp\b", r"\btarget stores\b"]),
    "Trump Media": ("DJT", [r"\btruth social\b", r"\btrump media\b", r"\bdjt stock\b", r"\$djt\b"]),
    "New York Times": ("NYT", [r"\bnew york times\b", r"\bnytimes\b"]),
    "Goldman Sachs": ("GS", [r"\bgoldman sachs\b"]),
    "Bank of America": ("BAC", [r"\bbank of america\b"]),
    "Citigroup": ("C", [r"\bcitibank\b", r"\bcitigroup\b"]),
    "Wells Fargo": ("WFC", [r"\bwells fargo\b"]),
    "Costco": ("COST", [r"\bcostco\b"]),
    "IBM": ("IBM", [r"\bibm\b"]),
    "Cisco": ("CSCO", [r"\bcisco\b"]),
    "Qualcomm": ("QCOM", [r"\bqualcomm\b"]),
    "Broadcom": ("AVGO", [r"\bbroadcom\b"]),
    "Chevron": ("CVX", [r"\bchevron\b"]),
    "Caterpillar": ("CAT", [r"\bcaterpillar\b"]),
    "Deere": ("DE", [r"\bjohn deere\b", r"\bdeere\b"]),
    "3M": ("MMM", [r"\b3m company\b"]),
    "Merck": ("MRK", [r"\bmerck\b"]),
    "Moderna": ("MRNA", [r"\bmoderna\b"]),
    "Johnson & Johnson": ("JNJ", [r"\bjohnson & johnson\b", r"\bjohnson and johnson\b"]),
    "UnitedHealth": ("UNH", [r"\bunitedhealth\b"]),
    "PayPal": ("PYPL", [r"\bpaypal\b"]),
    "Oracle": ("ORCL", [r"\boracle\b", r"\blarry ellison\b"]),
    "Salesforce": ("CRM", [r"\bsalesforce\b"]),
    "General Dynamics": ("GD", [r"\bgeneral dynamics\b"]),
    "Northrop Grumman": ("NOC", [r"\bnorthrop\b"]),
    "Raytheon": ("RTX", [r"\braytheon\b"]),
    "Coinbase": ("COIN", [r"\bcoinbase\b"]),
}
